const express = require("express");
const router = express.Router();
const {signup, login, getDoctors,provideAccess, getPatients} = require("../controllers/auth");
//router.post("/join", join);
router.post("/signup", signup);
router.post("/signin", login);
router.get("/doctors", getDoctors);
router.post('/access',provideAccess);
router.get('/patients/:id', getPatients);
module.exports = router;
